# Generated by Django 5.2.6 on 2025-09-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
